import {
  FiHome, FiGrid, FiBell, FiShoppingCart, FiUser, FiPackage, FiHeart,
  FiSearch, FiX, FiChevronLeft, FiChevronRight, FiChevronDown, FiChevronUp,
  FiPlus, FiMinus, FiTrash2, FiEdit2, FiCheck, FiCheckCircle,
  FiAlertCircle, FiInfo, FiAlertTriangle, FiArrowLeft, FiArrowRight,
  FiMenu, FiMail, FiPhone, FiMapPin, FiStar, FiClock, FiEye, FiEyeOff,
  FiLock, FiUnlock, FiLogOut, FiSettings, FiCreditCard, FiTruck,
  FiRefreshCw, FiCopy, FiShare2, FiDownload, FiUpload, FiCamera,
  FiSend, FiMessageSquare, FiThumbsUp, FiThumbsDown, FiSliders,
  FiList, FiMoreHorizontal, FiExternalLink, FiBookmark,
  FiGift, FiAward, FiDollarSign, FiPercent, FiTrendingUp, FiUsers,
  FiShield, FiPhoneCall, FiLinkedin, FiTwitter, FiInstagram, FiYoutube,
  FiFacebook, FiGithub, FiGlobe, FiSun, FiMoon, FiPrinter,
  FiClipboard, FiFileText, FiCalendar, FiPaperclip, FiSmile,
  FiMic, FiPlay, FiPause, FiSkipBack, FiSkipForward, FiHeart as FiHeartOutline,
} from 'react-icons/fi'

import {
  FaWhatsapp, FaGoogle, FaFacebook, FaLinkedin, FaTwitter, FaInstagram,
  FaYoutube, FaGithub, FaMicrosoft, FaApple, FaAmazonPay,
  FaGooglePay, FaCcVisa, FaCcMastercard, FaPaypal,
  FaTruck, FaShippingFast, FaBoxOpen,
  FaLeaf, FaIndustry, FaGem, FaFire, FaBolt, FaCrown,
  FaStar, FaStarHalfAlt, FaRegStar,
} from 'react-icons/fa'

import {
  GiSaltShaker, GiCrystalCluster, GiMountainCave, GiWavyItinerary,
  GiFactory, GiFruitBowl, GiMinerals, GiDeadlyStrike, GiCheckMark,
  GiHerbsBundle, GiHotSpices,
} from 'react-icons/gi'

import {
  BsWhatsapp, BsTelephone, BsEnvelope, BsGeoAlt, BsChatDots,
  BsCurrencyRupee, BsShieldCheck, BsPatchCheck, BsAward,
  BsTruck, BsBoxSeam, BsCart3, BsPerson, BsSearch,
} from 'react-icons/bs'

// MdOutlineSalt doesn't exist in react-icons/md; use GiSaltShaker instead

export const icons = {
  home: FiHome,
  grid: FiGrid,
  bell: FiBell,
  cart: FiShoppingCart,
  user: FiUser,
  package: FiPackage,
  heart: FiHeart,
  heartOutline: FiHeartOutline,
  search: FiSearch,
  close: FiX,
  chevronLeft: FiChevronLeft,
  chevronRight: FiChevronRight,
  chevronDown: FiChevronDown,
  chevronUp: FiChevronUp,
  plus: FiPlus,
  minus: FiMinus,
  trash: FiTrash2,
  edit: FiEdit2,
  check: FiCheck,
  checkCircle: FiCheckCircle,
  alertCircle: FiAlertCircle,
  info: FiInfo,
  alertTriangle: FiAlertTriangle,
  arrowLeft: FiArrowLeft,
  arrowRight: FiArrowRight,
  menu: FiMenu,
  mail: FiMail,
  phone: FiPhone,
  mapPin: FiMapPin,
  star: FiStar,
  clock: FiClock,
  eye: FiEye,
  eyeOff: FiEyeOff,
  lock: FiLock,
  unlock: FiUnlock,
  logout: FiLogOut,
  settings: FiSettings,
  creditCard: FiCreditCard,
  truck: FiTruck,
  refresh: FiRefreshCw,
  copy: FiCopy,
  share: FiShare2,
  download: FiDownload,
  upload: FiUpload,
  camera: FiCamera,
  send: FiSend,
  messageSquare: FiMessageSquare,
  thumbsUp: FiThumbsUp,
  thumbsDown: FiThumbsDown,
  sliders: FiSliders,
  list: FiList,
  gridView: FiGrid,
  moreHorizontal: FiMoreHorizontal,
  externalLink: FiExternalLink,
  bookmark: FiBookmark,
  gift: FiGift,
  award: FiAward,
  dollar: FiDollarSign,
  percent: FiPercent,
  trendingUp: FiTrendingUp,
  users: FiUsers,
  shield: FiShield,
  call: FiPhoneCall,
  globe: FiGlobe,
  sun: FiSun,
  moon: FiMoon,
  printer: FiPrinter,
  clipboard: FiClipboard,
  fileText: FiFileText,
  calendar: FiCalendar,
  paperclip: FiPaperclip,
  smile: FiSmile,
  mic: FiMic,
  play: FiPlay,
  pause: FiPause,
  facebook: FiFacebook,
  twitter: FiTwitter,
  instagram: FiInstagram,
  youtube: FiYoutube,
  linkedin: FiLinkedin,
  github: FiGithub,

  whatsapp: FaWhatsapp,
  google: FaGoogle,
  faFacebook: FaFacebook,
  faTwitter: FaTwitter,
  faInstagram: FaInstagram,
  faYoutube: FaYoutube,
  faLinkedin: FaLinkedin,
  faTruck: FaTruck,
  faShippingFast: FaShippingFast,
  faBoxOpen: FaBoxOpen,
  faSaltShaker: GiSaltShaker,
  faLeaf: FaLeaf,
  faIndustry: FaIndustry,
  faGem: FaGem,
  faFire: FaFire,
  faBolt: FaBolt,
  faCrown: FaCrown,
  faStar: FaStar,
  faStarHalfAlt: FaStarHalfAlt,
  faRegStar: FaRegStar,
  amazonPay: FaAmazonPay,
  googlePay: FaGooglePay,
  visa: FaCcVisa,
  mastercard: FaCcMastercard,
  paypal: FaPaypal,
  apple: FaApple,
  microsoft: FaMicrosoft,

  saltShaker: GiSaltShaker,
  crystalCluster: GiCrystalCluster,
  mountainCave: GiMountainCave,
  wavyItinerary: GiWavyItinerary,
  blackSalt: GiMinerals,
  factory: GiFactory,
  organic: GiHerbsBundle,
  spices: GiHotSpices,
  fruitBowl: GiFruitBowl,
  minerals: GiMinerals,
  deadStrike: GiDeadlyStrike,
  checkMark: GiCheckMark,

  bsWhatsapp: BsWhatsapp,
  bsTelephone: BsTelephone,
  bsEnvelope: BsEnvelope,
  bsGeoAlt: BsGeoAlt,
  bsChatDots: BsChatDots,
  bsCurrencyRupee: BsCurrencyRupee,
  bsShieldCheck: BsShieldCheck,
  bsPatchCheck: BsPatchCheck,
  bsAward: BsAward,
  bsTruck: BsTruck,
  bsBoxSeam: BsBoxSeam,
  bsCart3: BsCart3,
  bsPerson: BsPerson,
  bsSearch: BsSearch,

  mdSalt: GiSaltShaker,
}

export function Icon({ name, size = 20, color, className, style, onClick }) {
  const Component = icons[name]
  if (!Component) return null
  return <Component size={size} color={color} className={className} style={style} onClick={onClick} />
}

export const categoryIcons = {
  'Rock Salt': GiCrystalCluster,
  'Sea Salt': GiWavyItinerary,
  'Iodized Salt': GiSaltShaker,
  'Sendha Namak': GiMountainCave,
  'Black Salt': GiMinerals,
  'Industrial Salt': GiFactory,
  'Organic Salt': GiHerbsBundle,
  'Flavoured Salt': GiHotSpices,
}

export function CategoryIcon({ name, size = 24, color, className }) {
  const Component = categoryIcons[name]
  if (!Component) return <GiSaltShaker size={size} color={color} className={className} />
  return <Component size={size} color={color} className={className} />
}

export const vendorCertIcons = {
  'FSSAI': BsShieldCheck,
  'ISO 22000': FiShield,
  'ISO 9001': FiShield,
  'ISO 14001': FiShield,
  'BIS Certified': BsPatchCheck,
  'Organic India': GiHerbsBundle,
  'Organic Certified': GiHerbsBundle,
  'Ayush Certified': GiHerbsBundle,
  'GMP': BsAward,
  'GI Tagged': GiMountainCave,
  'USDA Organic': GiHerbsBundle,
  'EU Organic': GiHerbsBundle,
  'India Organic': GiHerbsBundle,
  'HACCP': BsShieldCheck,
  'REACH Compliant': FiGlobe,
  'Mines Safety': GiMinerals,
  'FDA Registered': FiClipboard,
}

export const statIcons = {
  'Verified Vendors': FaIndustry,
  'Salt Varieties': GiSaltShaker,
  'States Covered': FiGlobe,
  'Delivered Today': FiTruck,
  'Orders': FiPackage,
  'Buyers': FiUsers,
  'Products': GiSaltShaker,
}

export const trustIcons = {
  'FSSAI Certified': GiCheckMark,
  'ISO Verified': FiShield,
  '100% Pure': GiCrystalCluster,
  'Secure Payments': FiLock,
  'Pan India Delivery': FiTruck,
}

export default Icon
